server:
  port: 8080
spring:
  application:
    name: datjpa2
  datasource:
    url: jdbc:mysql://localhost:8889/schooldb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka